### ISSUE TITLE
Idea proposal 

### ISSUE THREAD

**Issue by rjm-codes** [paradox-bot/paradox#31]
On startup, have the client ask the end user (administrator that’s performing the restarting of the bot) to specify a playing status or 'none'.

**Comment by rjm-codes** [comment]
Possibly using Python's `input()` function if you're to do it via shell.

**Comment by Sodre177** [comment]
Interesting idea, however the startup is almost never performed manually. The bot is pulled from github and rebooted via a script triggered from a discord command to another bot.

**Comment by rjm-codes** [comment]
oh

**Comment by rjm-codes** [comment]
invalid...? Do you wish to explain why?

**Comment by ghost** [comment]
It would just be annoying? It should just keep its previous status until it’s changed

**Comment by rjm-codes** [comment]
lol

**Comment by rjm-codes** [comment]
ur doing this because u hate me

**Comment by rjm-codes** [comment]
at least i can debate and talk to pue about things compared to u

**Comment by whomhasfallen** [comment]
🤔

**Comment by ghost** [comment]
I don’t need your bullshit, bye.

**Comment by whomhasfallen** [comment]
😆 Turned into a meme pull, now?
